/**:
  ros__parameters:
    # General Parameters
    use_sim_time: false

    # Collision Avoidance
    collision_avoidance:
      distance_reduce_velocity: 0.4
      distance_velocity_zero: 0.05
      enable: true
      
    # Diagnostic
    diagnostic_updater:
      period: 1.0
      use_fqn: false
      
    # Sensors
    imu:
      fusion_weight: 0.029999999329447746
      mounting_orientation:
        roll: -1.5707963705062866
        pitch: -1.5707963705062866
        yaw: -1.5707963705062866
      publish_orientation_without_yaw_tf: true
      publish_tf: true
    
    # TF2
    tf:
      base_frame: base_link
      footprint_frame: base_footprint
      publishing_interval_ms: 50
    
    # Odometry
    odometry:
      publishing_interval_ms: 50
      publishing_tf: true

    # Kinematic
    mecanum:
      length:
        x: 0.25
        y: 0.36000001430511475
      wheel_diameter: 0.10000000149011612
      
    skid:
      length:
        x: 0.25
        y: 0.3199999928474426
      wheel_diameter: 0.17000000178813934
      
    # Motor
    motor_a:
      closed_loop: true
      index: 2
      max_rpm: 100.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5
    motor_b:
      closed_loop: true
      index: 1
      max_rpm: 100.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5
    motor_c:
      closed_loop: true
      index: 4
      max_rpm: 100.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5
    motor_d:
      closed_loop: true
      index: 3
      max_rpm: 100.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5

    motor_controller_0:
      can_id:
        input: 1024
        output: 1152
      control_frequency: 16000
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      timeout_ms: 500
      weight_low_pass_encoder: 0.3
      weight_low_pass_set_point: 0.2

    motor_controller_1:
      can_id:
        input: 1025
        output: 1153
      control_frequency: 16000
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      timeout_ms: 500
      weight_low_pass_encoder: 0.3
      weight_low_pass_set_point: 0.2
    
    # TOF Sensors
    tof_sensor_ring_left:
      can_id:
        measurement_complete: 776
        trigger: 904
      front:
        virtual_range_sensor: true
        fov:
          horizontal: 0.7853981852531433
          vertical: 0.7853981852531433
        measurement_interval_ms: 100
        number_of_zones:
          horizontal: 8
          vertical: 8
        sensor_id: 2
        transform:
          orientation:
            roll: 1.570796327
            pitch: -0.343829863        # -19,7° (TOF-sensor is angled on PCB)
            yaw: 1.570796327
          translation:
            x: 0.17
            y: 0.063
            z: 0.045
      measurement_interval: 100
      rear:
        virtual_range_sensor: true
        fov:
          horizontal: 0.7853981852531433
          vertical: 0.7853981852531433
        measurement_interval_ms: 100
        number_of_zones:
          horizontal: 8
          vertical: 8
        sensor_id: 1
        transform:
          orientation:
            roll: 0.0
            pitch: 4.71238898
            yaw: 0.0
          translation:
            x: -0.17
            y: 0.063
            z: 0.05
    tof_sensor_ring_right:
      can_id:
        measurement_complete: 776
        trigger: 904
      front:
        virtual_range_sensor: true
        fov:
          horizontal: 0.7853981852531433
          vertical: 0.7853981852531433
        measurement_interval_ms: 100
        number_of_zones:
          horizontal: 8
          vertical: 8
        sensor_id: 2
        transform:
          orientation:
            roll: -1.570796327
            pitch: -0.343829863        # -19,7° (TOF-sensor is angled on PCB)
            yaw: -1.570796327
          translation:
            x: 0.17
            y: -0.063
            z: 0.045
      measurement_interval: 100
      rear:
        virtual_range_sensor: true
        fov:
          horizontal: 0.7853981852531433
          vertical: 0.7853981852531433
        measurement_interval_ms: 100
        number_of_zones:
          horizontal: 8
          vertical: 8
        sensor_id: 1
        transform:
          orientation:
            roll: 0.0
            pitch: 1.570796327
            yaw: 3.141592654
          translation:
            x: -0.17
            y: -0.063
            z: 0.05
