/**:
  ros__parameters:
# General Parameters
    enable_collision_avoidance: true
    tf_base_frame: base_link
    tf_footprint_frame: base_footprint
    use_sim_time: false

# Collision Avoidance
    collision_avoidance:
      enable: true
      distance_reduce_velocity: 0.6
      distance_velocity_zero: 0.05

# IMU Sensor
    imu:
      fusion_weight: 0.005
      mounting_orientation:
        pitch: 0.0
        roll: 0.0
        yaw: 0.0 
      publish_tf: true
      publish_orientation_without_yaw_tf : true      

# Motor Controller
    motor_a:
      closed_loop: true    
      control_frequency: 16000
      timeout_ms: 500
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

    motor_b:
      closed_loop: true    
      control_frequency: 16000
      timeout_ms: 500
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

    motor_c:
      closed_loop: true    
      control_frequency: 16000
      timeout_ms: 500
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

    motor_d:
      closed_loop: true    
      control_frequency: 16000
      timeout_ms: 500
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

# Range Sensor
    range:  
      front:
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01
        
        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01

      rear:    
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01

        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01

# Drive Kinematic
    skid:
      length:
        x: 0.25
        y: 0.32
      wheel_diameter: 0.17

    mecanum:
      length:
        x: 0.25
        y: 0.36
      wheel_diameter: 0.1
