/**:
  ros__parameters:
    # Motor Controller
    motor_controller_0:
      can_id: 0
      control_frequency: 16000
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      timeout_ms: 500
      weight_low_pass_encoder: 0.3
      weight_low_pass_set_point: 0.2

    motor_controller_1:
      can_id: 1
      control_frequency: 16000
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      timeout_ms: 500
      weight_low_pass_encoder: 0.3
      weight_low_pass_set_point: 0.2

    # Motor
    motor_a:
      closed_loop: true
      index: 2
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5
    motor_b:
      closed_loop: true
      index: 1
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5
    motor_c:
      closed_loop: true
      index: 4
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5
    motor_d:
      closed_loop: true
      index: 3
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 5.0
        kp: 0.5      