/**:
  ros__parameters:
    # General Parameters
    use_sim_time: false

    # Collision Avoidance
    collision_avoidance:
      distance_reduce_velocity: 0.4
      distance_velocity_zero: 0.05
      enable: true
      
    # Diagnostic
    diagnostic_updater:
      period: 1.0
      use_fqn: false
      
    # Sensors
    imu:
      fusion_weight: 0.029999999329447746
      mounting_orientation:
        roll: -1.5707963705062866
        pitch: -1.5707963705062866
        yaw: -1.5707963705062866
      publish_orientation_without_yaw_tf: true
      publish_tf: true
    
    # TF2
    tf:
      base_frame: base_link
      footprint_frame: base_footprint
      publishing_interval_ms: 50
    
    # Odometry
    odometry:
      publishing_interval_ms: 50
      publishing_tf: true

    # Motor Controller
    motor_controller_0:
      can_id: 0
      control_frequency: 16000
      timeout_ms: 500
      input_filter_weight: 0.5

    motor_controller_1:
      can_id: 1
      control_frequency: 16000
      timeout_ms: 500
      input_filter_weight: 0.5

    # Range Sensor
    range:  
      front:
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01
        
        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01

      rear:    
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01

        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.01

    # Drive Kinematic
    skid:
      length:
        x: 0.25
        y: 0.32
      wheel_diameter: 0.17

    mecanum:
      length:
        x: 0.25
        y: 0.36
      wheel_diameter: 0.1
