/**:
  ros__parameters:
    # General Parameters
    use_sim_time: false

    # Collision Avoidance    
    collision_avoidance:
      distance_reduce_velocity: 0.4
      distance_velocity_zero: 0.05
      enable: false

    # Diagnostic
    diagnostic_updater:
      period: 1.0
      use_fqn: false

    # Sensors
    imu:
      fusion_weight: 0.029999999329447746
      mounting_orientation:
        pitch: -1.5707963705062866
        roll: -1.5707963705062866
        yaw: -1.5707963705062866

    # TF2
    tf:
      base_frame: base_link
      footprint_frame: base_footprint
      publishing_interval_ms: 100
    
    # Odometry
    odometry:
      publishing_interval_ms: 100
      publishing_tf: true    

    # Axis
    number_of_axes: 3    
    axis_1:
      skid:
        length:
          x: 0.14
          y: 0.08
        wheel_diameter: 0.113
    axis_2:
      skid:
        length:
          x: 0.0
          y: 0.27
        wheel_diameter: 0.113
    axis_3:
      skid:
        length:
          x: -0.14
          y: 0.08
        wheel_diameter: 0.113

    # Motor Controller
    motor_controller_0:
      can_id: 0
      control_frequency: 16000
      timeout_ms: 500
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8      

    motor_controller_1:
      can_id: 1
      control_frequency: 16000
      timeout_ms: 500
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8   

    motor_controller_2:
      can_id: 2
      control_frequency: 16000
      timeout_ms: 500
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8      

    # Motor
    motor_a:
      closed_loop: true
      index: 0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5
  
    motor_b:
      closed_loop: true
      index: 0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5

    motor_c:
      closed_loop: true
      index: 0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5

    motor_d:
      closed_loop: true
      index: 0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5

    motor_e:
      closed_loop: true
      index: 0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5

    motor_f:
      closed_loop: true
      index: 0
      max_rpm: 90.0
      pid:
        kd: 0.0
        ki: 7.0
        kp: 0.5
  