version: "2.4"

services:
    eduard-ipc127e:
        image: eduartrobotik/eduard-ipc127e:0.4.1
        container_name: eduard-ipc127e-ie-app-0.4.1
        # debugging command for level 2 network access.
        # command: bash -c "sudo apt-get update && sudo apt-get install -y iproute2 net-tools && ip addr && ip route list && printenv && source /home/user/ros/install/setup.bash && export RMW_IMPLEMENTATION=rmw_fastrtps_cpp && ros2 topic list && ros2 daemon start && sudo netstat -gn &&  ros2 launch edu_robot eduard-ipc127e.launch.py"
        command: bash -c 'ros2 launch edu_robot eduard-ipc127e.launch.py'
        restart: on-failure
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard
        networks:
            - proxy-redirect
            - zzz_layer2_net1
            # - zzz_layer2_net2
        volumes:
            - './publish/:/publish/'
            - './cfg-data/:/cfg-data/'
            - './launch_content:/home/user/ros/launch_content:r'            
        ports:
            - "1234:1234/udp"

networks:
    proxy-redirect:
        external: true
    zzz_layer2_net1:
        name: zzz_layer2_net1
        external: true
    # zzz_layer2_net2:
    #     name: zzz_layer2_net2
    #     external: true
