version: "2.4"

services:
    eduard-ipc127e:
        image: eduartrobotik/eduard-ipc127e:0.4.1
        container_name: eduard-blue-ipc127e-ie-app-0.4.1
        restart: on-failure
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/blue
        networks:
            - proxy-redirect
            - zzz_layer2_net1
        volumes:
            - './publish/:/publish/'
            - './cfg-data/:/cfg-data/'
        ports:
            - "1234:1234/udp"

networks:
    proxy-redirect:
        external: true
    zzz_layer2_net1:
        name: zzz_layer2_net1
        external: true
