version: "3.0"

services:
    eduard-raspberry-pi:
        image: eduartrobotik/eduart-robot:1.0.0
        container_name: eduard-raspberry-1.0.0
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}            
        network_mode: "host"
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch eduard-360-pi.launch.py'
        volumes:
            - './launch_content:/home/user/ros/launch_content:r'
        devices:
            - '/dev:/dev'

    eduard-robot-control:
        image: eduartrobotik/eduart-robot-control:0.5.0
        container_name: eduard-robot-control-raspberry-0.5.0
        user: user
        group_add:
            - "102"
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}            
        network_mode: "host"
        devices:
            - '/dev:/dev'
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch robot_remote_control_raspberry.launch.py'            
        volumes:
            - '/dev:/dev'
            - './launch_content:/home/user/ros/launch_content:r'            
